#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""ViceMe Skill 免 CLI 安装/试用脚本。

作品页 `.md` 口令的无 `viceme` 分支调用本脚本;也可独立使用:

    curl -fsSL https://s3.viceme.cn/skills/use-a-skill/scripts/trial.py \\
      | python3 - install --product <product-id> --market cn

    curl -fsSL https://s3.viceme.cn/skills/use-a-skill/scripts/trial.py \\
      | python3 - use --product <product-id> --market cn

Windows (PowerShell;先落盘再执行,避开 PS5.1 管道编码转换,`py` 是
python.org 安装必装的启动器,没有时改用 `python`):

    curl.exe -fsSL https://s3.viceme.cn/skills/use-a-skill/scripts/trial.py -o $env:TEMP\viceme-trial.py
    py $env:TEMP\viceme-trial.py install --product <product-id> --market cn

设计约束(与 CLI 实现对齐,改动前先读 CLI 的 skill_trial.go):
- 匿名试用契约:POST /v1/skills/<id>/trial-grants、POST /v1/skills/<id>/trial-use、
  GET /v1/downloads/trial/<id>?installId=。installId 为 UUID,凭证不可变,
  计数权威在服务端;本机文件只是凭证的载体。
- 下载完整性 = SHA-256 对服务端返回的 artifactDigest,不依赖签名算法。
- 门禁入口与内部规则路径和 CLI 对齐;本机凭证购买后由当前路线重装正式包。
- 凭证落 ~/.viceme/trial/<product>.json(0600);CLI 的 ensureSkillTrialGrant
  在无本地凭证时会先收编该文件,两条安装路共用同一个 grant。
- 输出始终是单行 JSON,供 AI 助手解析分支。
"""

import argparse
import hashlib
import io
import json
import os
import stat
import sys
import tempfile
import time
import urllib.error
import urllib.parse
import urllib.request
import uuid
import zipfile
from datetime import datetime, timezone
from contextlib import contextmanager

SCRIPT_ORIGIN = {
    "cn": "https://s3.viceme.cn",
    "global": "https://s3.viceme.ai",
}
API_ORIGIN = {
    "cn": "https://api.viceme.cn",
    "global": "https://api.viceme.ai",
}
INSTALL_DOC_ORIGIN = {
    "cn": "https://s3.viceme.cn/start/agent-install.md",
    "global": "https://s3.viceme.ai/start/agent-install.md",
}
SCRIPT_RELATIVE_PATH = "/skills/use-a-skill/scripts/trial.py"

GATE_MARKER = "<!-- viceme-trial:v1"
GATE_END = "<!-- /viceme-trial:v1 -->"
RUNTIME_PATH = "references/viceme-runtime.md"
RUNTIME_MARKER = "<!-- viceme-trial-runtime:v1"
GATE_TAIL = "转正，再继续任务。"
DISABLED_MARKER = "<!-- viceme-trial-disabled:v1"

HTTP_TIMEOUT = 30
MAX_FILES = 1000
MAX_FILE_BYTES = 10 << 20
MAX_TOTAL_BYTES = 50 << 20
LOCK_STALE_SECONDS = 300
LOCK_WAIT_SECONDS = 10

# Content-addressed resources are generated by cmd/skills-archive. Verify before
# executing the vendored encoder; never install a global Python dependency.
WIDGET_DIGESTS = {
    "payment.html": "7fac100b7b582166d62807f3ef5319362152f2a96d4a1f43b4be052f2ed09a12",
    "qrcodegen.py": "9f4ed1dd201dcb92b1bc0d6e14f46c754bcff0ce48580c5d7e8ace8f6926c8ef",
}


class Failure(Exception):
    """业务失败:已经能给出确定的单行 JSON 结论。"""

    def __init__(self, code, message, **fields):
        super().__init__(message)
        self.code = code
        self.message = message
        self.fields = fields


def emit(payload):
    sys.stdout.write(json.dumps(payload, ensure_ascii=False, sort_keys=True) + "\n")


def emit_ok(payload):
    payload["ok"] = True
    emit(payload)
    return 0


def emit_failure(failure):
    payload = {"ok": False, "code": failure.code, "message": failure.message}
    payload.update(failure.fields)
    emit(payload)
    return 1


def script_url(market):
    return SCRIPT_ORIGIN[market] + SCRIPT_RELATIVE_PATH


def install_doc_url(market):
    return INSTALL_DOC_ORIGIN[market]


def api_endpoint(market, path):
    return API_ORIGIN[market] + path


def api_request(market, method, path, body=None):
    data = None
    headers = {"Accept": "application/json"}
    if body is not None:
        data = json.dumps(body).encode("utf-8")
        headers["Content-Type"] = "application/json"
    request = urllib.request.Request(api_endpoint(market, path), data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(request, timeout=HTTP_TIMEOUT) as response:
            raw = response.read()
    except urllib.error.HTTPError as error:
        # 错误体只回放标准 JSON 契约里的 message/code;非 JSON 响应
        # (网关/代理错误页)可能携带内部主机名、路径甚至凭证,不回显。
        detail = _error_detail(error)
        message = "ViceMe API 返回错误(%s %s)" % (error.code, path)
        if detail:
            message += ": %s" % detail
        raise Failure("API_ERROR", message, status=error.code, detail=detail) from None
    except urllib.error.URLError as error:
        # reason 可能携带代理地址/凭证/本机路径,只保留异常类型名。
        raise Failure("NETWORK_ERROR", "无法连接 ViceMe API(%s): %s" % (path, type(error.reason).__name__)) from None
    if not raw:
        return {}
    try:
        return json.loads(raw.decode("utf-8"))
    except ValueError:
        raise Failure("API_RESPONSE_INVALID", "ViceMe API 返回了无法解析的响应(%s)" % path) from None


def _error_detail(error):
    """提取标准错误契约的 message/code;非 JSON 错误体一律不回显。"""
    try:
        raw = error.read()
    except Exception:  # noqa: BLE001 - 错误体读取失败时退回状态码
        return ""
    if isinstance(raw, bytes):
        raw = raw.decode("utf-8", "replace")
    try:
        parsed = json.loads(raw)
    except Exception:  # noqa: BLE001 - 非 JSON 错误体(网关/代理错误页)
        return ""
    return str(parsed.get("message") or parsed.get("code") or "")


def http_download(url):
    request = urllib.request.Request(url, headers={"Accept": "application/octet-stream"})
    try:
        with urllib.request.urlopen(request, timeout=HTTP_TIMEOUT) as response:
            return response.read()
    except urllib.error.HTTPError as error:
        # 错误输出不得携带 URL:下载地址是短期签名凭证(X-Amz-Signature
        # 等),进 AI 对话或日志等于泄露临时凭证。只报状态码。
        raise Failure("DOWNLOAD_ERROR", "下载 Skill 包失败(HTTP %s)" % error.code) from None
    except urllib.error.URLError as error:
        # 原始 reason 可能携带代理地址等本机信息,只保留异常类型名。
        raise Failure("NETWORK_ERROR", "下载 Skill 包失败: %s" % type(error.reason).__name__) from None


# ---------------------------------------------------------------------------
# 本地状态:凭证文件与轻量进程锁
# ---------------------------------------------------------------------------


def trial_state_path(product_id):
    return os.path.join(home_directory(), ".viceme", "trial", product_id + ".json")


def home_directory():
    return os.environ.get("HOME") or os.path.expanduser("~")


def load_trial_state(product_id):
    path = trial_state_path(product_id)
    try:
        with open(path, "r", encoding="utf-8") as handle:
            state = json.load(handle)
    except FileNotFoundError:
        return None
    except (OSError, ValueError):
        return None
    if not isinstance(state, dict) or not state.get("installId") or not state.get("secret"):
        return None
    return state


def save_trial_state(product_id, state):
    path = trial_state_path(product_id)
    try:
        os.makedirs(os.path.dirname(path), mode=0o700, exist_ok=True)
    except OSError as error:
        # 消息不含路径:本机目录属于不应进 AI 对话/日志的信息。
        raise Failure("STATE_DIR_PERMISSION_DENIED", "无法创建试用状态目录(权限不足),请检查主目录可写") from error
    previous = os.stat(path).st_mode & 0o777 if os.path.exists(path) else 0o600
    # 原子替换:并发读者(Go 侧接管/清理)要么看到旧文件要么看到新文件,
    # 永远不会读到写了一半的 JSON。
    temporary = path + ".tmp"
    with open(temporary, "w", encoding="utf-8") as handle:
        json.dump(state, handle, ensure_ascii=False, indent=2, sort_keys=True)
        handle.write("\n")
        handle.flush()
        os.fsync(handle.fileno())
    os.chmod(temporary, previous if previous else 0o600)
    os.replace(temporary, path)


class ProductLock:
    """跨进程串行化同一 Product 的 install/use,避免并发改写状态文件。"""

    def __init__(self, product_id):
        self.path = trial_state_path(product_id) + ".lock"
        self.handle = None

    def __enter__(self):
        try:
            os.makedirs(os.path.dirname(self.path), mode=0o700, exist_ok=True)
        except OSError as error:
            raise Failure("STATE_DIR_PERMISSION_DENIED", "无法创建试用状态目录(权限不足),请检查主目录可写") from error
        deadline = time.time() + LOCK_WAIT_SECONDS
        while True:
            try:
                self.handle = os.open(self.path, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
                os.write(self.handle, str(os.getpid()).encode("ascii"))
                return self
            except FileExistsError:
                pass  # 被 Unix 进程占用:走下方超时路径。
            except PermissionError as error:
                # Windows 共享冲突与 Unix「无权创建」同名:靠锁文件是否
                # 存在区分——不存在即为无权创建(目录不可写),立即报错,
                # 不得进入重试循环。
                try:
                    os.stat(self.path)
                except FileNotFoundError:
                    raise Failure(
                        "STATE_LOCK_PERMISSION_DENIED",
                        "无法创建试用状态锁文件(目录不可写或无权限),请检查主目录可写",
                    ) from error
                except OSError:
                    pass  # 存在但暂时不可 stat(共享冲突):按被占处理。
            # 每一轮都先做截止检查再休眠:任何路径都不允许无休眠地
            # 回到循环顶部,否则权限异常会变成 CPU 空转死循环。
            if time.time() > deadline:
                raise Failure("STATE_LOCK_BUSY", "另一个 ViceMe 试用操作正在进行,请稍后重试")
            try:
                if time.time() - os.stat(self.path).st_mtime > LOCK_STALE_SECONDS:
                    remove_path(self.path)
            except OSError:
                pass
            time.sleep(0.2)

    def __exit__(self, exc_type, exc_value, traceback):
        if self.handle is not None:
            os.close(self.handle)
        try:
            os.remove(self.path)
        except OSError:
            pass
        return False


# ---------------------------------------------------------------------------
# install 子命令
# ---------------------------------------------------------------------------


def command_install(market, product_id, agent="auto"):
    state = load_trial_state(product_id)
    if state and state.get("purchase"):
        return command_purchase(market, product_id, agent=agent)
    access = api_request(market, "GET", "/v1/skills/%s/access" % urllib.parse.quote(product_id, safe=""))
    trial = access.get("trial") or {}
    if access.get("isFree"):
        kind = "free"
        grant = None
    elif trial.get("available"):
        kind = "trial"
        grant = ensure_trial_grant(market, product_id)
    else:
        purchase_url = access.get("purchaseUrl") or ""
        raise Failure(
            "PURCHASE_REQUIRED",
            "该 Skill 需要登录购买后才能安装;请打开作品页完成支付,或安装 ViceMe CLI 后使用 viceme skill install",
            purchaseUrl=purchase_url,
            installDocUrl=install_doc_url(market),
        )

    if kind == "trial":
        download = api_request(market, "GET", "/v1/downloads/trial/%s?installId=%s" % (urllib.parse.quote(product_id, safe=""), urllib.parse.quote(grant["installId"])))
    else:
        download = api_request(market, "GET", "/v1/downloads/free/%s" % urllib.parse.quote(product_id, safe=""))
    return finish_install(market, product_id, agent, access, download, kind, grant)


def finish_install(market, product_id, agent, access, download, kind, grant=None):
    release = access.get("release") or {}
    if download.get("releaseId") != release.get("id") or download.get("artifactDigest") != release.get("artifactDigest"):
        raise Failure("DOWNLOAD_RECEIPT_MISMATCH", "下载授权与当前发布版本不一致,请重试")

    archive = http_download(download["url"])
    digest = hashlib.sha256(archive).hexdigest()
    if digest != download.get("artifactDigest"):
        raise Failure("ARTIFACT_DIGEST_MISMATCH", "下载的 Skill 包与发布版本不匹配(完整性校验失败)")

    files = extract_skill_package(archive)
    if kind == "trial":
        inject_trial_gate(files, market, product_id)
    installed_name = resolve_installed_name(files, access)
    # 与 Go 的正式版安装/停用共锁,防止耗尽响应覆盖刚安装的正式版。
    with ProductLock(product_id):
        current = load_trial_state(product_id)
        if kind == "trial" and current and current.get("purchase"):
            raise Failure("PURCHASE_IN_PROGRESS", "本机已有购买流程,请运行 purchase 恢复,不能覆盖为试用版")
        installer = install_owned_to_roots if kind == "owned" else install_to_roots
        roots = installer(files, installed_name, product_id, release.get("id", ""), agent)
        if kind == "trial":
            for root, skip in roots:
                if not skip:
                    verify_installed_trial_gate(root, files)
    succeeded = [root for root, skip in roots if not skip]
    if not succeeded or (kind == "owned" and any(skip for _, skip in roots)):
        # 全部目标都被拒绝覆盖(非 ViceMe 管理/属其他 Product)时,一个文件都没
        # 落盘;必须报错而不是谎报安装成功。
        raise Failure(
            "INSTALL_FAILED",
            "没有可写入的目标目录,未安装任何文件;跳过原因见 skipped 字段",
            skipped=[{"root": root, "reason": skip} for root, skip in roots if skip],
        )

    result = {
        "action": "installed",
        "kind": kind,
        "productId": product_id,
        "installedName": installed_name,
        "roots": succeeded,
        "skippedRoots": [skip for _, skip in roots if skip],
        "releaseId": release.get("id"),
        "artifactDigest": digest,
    }
    if kind == "trial":
        result["trial"] = {
            "installId": grant["installId"],
            "limitUses": grant.get("limitUses"),
            "remainingUses": grant.get("remainingUses"),
        }
    result["nextAction"] = "READ_SKILL_MD_AND_INTRODUCE"
    result["onboardingGuideUrl"] = SCRIPT_ORIGIN[market] + "/skills/_widgets/README.md"
    result["onboardingTemplateUrl"] = SCRIPT_ORIGIN[market] + "/skills/_widgets/onboarding.html"
    if kind == "owned":
        result["allowed"] = True
        result["owned"] = True
        result["nextAction"] = "CONTINUE_ORIGINAL_TASK_WITH_INSTALLED_SKILL"
    return emit_ok(result)


def ensure_trial_grant(market, product_id):
    with ProductLock(product_id):
        state = load_trial_state(product_id)
        if state:
            # 幂等回访:服务端按 (productId, installId) 返回当前余量,不发新凭证。
            grant = api_request(market, "POST", "/v1/skills/%s/trial-grants" % urllib.parse.quote(product_id, safe=""), {"installId": state["installId"]})
            install_id = grant.get("installId") or state["installId"]
            secret = grant.get("secret") or state["secret"]
        else:
            install_id = str(uuid.uuid4())
            grant = api_request(market, "POST", "/v1/skills/%s/trial-grants" % urllib.parse.quote(product_id, safe=""), {"installId": install_id})
            secret = grant.get("secret")
            if not secret:
                raise Failure("TRIAL_GRANT_INVALID", "试用凭证发放异常(未携带 secret),请重试")
            install_id = grant.get("installId") or install_id
        # 未确认的幂等键属于 (installId, requestId):同凭证重装必须原样保留,
        # 否则响应未知的那次使用会在下一次 use 换新键、被服务端再扣一次;
        # 换了新凭证(installId 变化)时旧键无法在新 grant 上回放,丢弃。
        previous = state or {}
        merged = dict(previous) if previous.get("installId") == install_id else {}
        merged.update({
            "installId": install_id,
            "secret": secret,
            "productId": product_id,
            "market": market,
        })
        if previous.get("installId") == install_id and previous.get("pendingRequestId"):
            merged["pendingRequestId"] = previous["pendingRequestId"]
        save_trial_state(product_id, merged)
        return {
            "installId": install_id,
            "secret": secret,
            "limitUses": grant.get("limitUses"),
            "remainingUses": grant.get("remainingUses"),
        }


# ---------------------------------------------------------------------------
# use 子命令
# ---------------------------------------------------------------------------


def command_use(market, product_id):
    current = load_trial_state(product_id)
    if current and current.get("purchase"):
        return command_purchase(market, product_id)
    if not load_trial_state(product_id):
        raise Failure(
            "TRIAL_GRANT_MISSING",
            "本机没有该 Skill 的试用凭证;先运行 install 子命令,或安装 ViceMe CLI 后使用 viceme skill install",
            installDocUrl=install_doc_url(market),
            scriptUrl=script_url(market),
        )
    with ProductLock(product_id):
        # 锁内重读权威状态:锁外快照可能错过其他进程刚写入的未确认幂等键,
        # 沿用陈旧快照会把已扣次的使用当成新使用、生成新键重复扣。
        # 未确认的 pending 幂等键优先重放:服务端按 requestId 回放旧结果,不重复扣次;
        # 网络错误/5xx 时保留 pending:服务端可能已扣次只是响应未送达,重试必须
        # 复用同一幂等键;换新键会对同一使用二次扣。
        state = load_trial_state(product_id)
        if not state:
            raise Failure(
                "TRIAL_GRANT_MISSING",
                "本机没有该 Skill 的试用凭证;先运行 install 子命令,或安装 ViceMe CLI 后使用 viceme skill install",
                installDocUrl=install_doc_url(market),
                scriptUrl=script_url(market),
            )
        request_id = state.get("pendingRequestId") or str(uuid.uuid4())
        state["pendingRequestId"] = request_id
        save_trial_state(product_id, state)
        use = api_request(
            market,
            "POST",
            "/v1/skills/%s/trial-use" % urllib.parse.quote(product_id, safe=""),
            {"installId": state["installId"], "secret": state["secret"], "requestId": request_id},
        )
        validate_trial_use(use)
        state.pop("pendingRequestId", None)
        save_trial_state(product_id, state)
        disabled_count = 0
        if use["allowed"] is False:
            disabled_count = suspend_trial_skills(market, product_id, use["purchaseUrl"])

    if use.get("allowed"):
        remaining = use.get("remainingUses")
        limit = use.get("limitUses")
        return emit_ok({
            "allowed": True,
            "remainingUses": remaining,
            "limitUses": limit,
            "lastUse": remaining == 0,
            "requestId": request_id,
            "nextAction": "CONTINUE_TASK",
        })
    purchase_url = use.get("purchaseUrl") or ""
    return emit_ok({
        "allowed": False,
        "reason": use.get("reason") or "TRIAL_EXHAUSTED",
        "purchaseUrl": purchase_url,
        "installDocUrl": install_doc_url(market),
        "nextAction": "PURCHASE_REQUIRED",
        "disabledSkillCount": disabled_count,
        "message": "试用已用完。运行本脚本 purchase --wait 0 展示支付 Widget,再运行 purchase --wait 60 确认付款并安装正式包;无需安装 CLI 或登录。购买链接仅供稍后查看商品。",
    })


def command_status(market, product_id):
    state = require_trial_state(market, product_id)
    grant = api_request(market, "POST", "/v1/skills/%s/trial-grants" % product_id, {"installId": state["installId"]})
    if grant.get("installId") != state["installId"] or type(grant.get("remainingUses")) is not int or type(grant.get("limitUses")) is not int or not 0 <= grant["remainingUses"] <= grant["limitUses"] or grant["limitUses"] <= 0:
        raise Failure("TRIAL_STATUS_INVALID", "无法确认剩余次数,请重试查询")
    return emit_ok({"productId": product_id, "remainingUses": grant["remainingUses"], "limitUses": grant["limitUses"], "nextAction": "SHOW_REMAINING_USES"})


def require_trial_state(market, product_id):
    state = load_trial_state(product_id)
    if not state or state.get("productId") != product_id or state.get("market") != market:
        raise Failure("TRIAL_GRANT_MISSING", "本机没有该商品在当前市场的试用凭证,不能继续购买或恢复")
    return state


def purchase_request(market, product_id, state, action="", extra=None):
    body = {"installId": state["installId"], "secret": state["secret"]}
    body.update(extra or {})
    return api_request(market, "POST", "/v1/skills/%s/trial-purchase%s" % (product_id, "/" + action if action else ""), body)


def validate_purchase(order, product_id, order_no=None):
    valid = isinstance(order, dict) and order.get("productId") == product_id and order.get("status") in ("PENDING", "PAID", "CLOSED")
    valid = valid and isinstance(order.get("orderNo"), str) and 6 <= len(order["orderNo"]) <= 40 and (order_no is None or order["orderNo"] == order_no)
    valid = valid and type(order.get("amountCents")) is int and order["amountCents"] >= 0 and order.get("currency") == "CNY" and isinstance(order.get("title"), str)
    try:
        expires = datetime.fromisoformat(order["expiresAt"].replace("Z", "+00:00"))
        valid = valid and expires.tzinfo is not None
    except (KeyError, ValueError, TypeError, AttributeError):
        valid = False
    if not valid:
        raise Failure("PURCHASE_RESPONSE_INVALID", "订单响应不完整,请保留本机购买记录并重试")


def command_purchase(market, product_id, wait=0, agent="auto"):
    with ProductLock(product_id):
        state = require_trial_state(market, product_id)
        purchase = state.get("purchase")
        if not purchase or purchase.get("closed"):
            purchase = {"clientRequestId": str(uuid.uuid4())}
            state["purchase"] = purchase
            save_trial_state(product_id, state)
        presented = purchase.get("presented") is True
        if purchase.get("orderNo"):
            order = purchase_request(market, product_id, state, "status", {"orderNo": purchase["orderNo"]})
        else:
            order = purchase_request(market, product_id, state, extra={"clientRequestId": purchase["clientRequestId"], "locale": "zh-CN" if market == "cn" else "en-US"})
        validate_purchase(order, product_id, purchase.get("orderNo"))
        if purchase.get("orderNo") and order["status"] == "PENDING" and not order.get("paymentAction") and datetime.fromisoformat(order["expiresAt"].replace("Z", "+00:00")) > datetime.now(timezone.utc):
            # Resume this order after an uncertain provider response. Status
            # polling below is read-only and never opens another payment.
            order = purchase_request(market, product_id, state, extra={"clientRequestId": purchase["clientRequestId"], "locale": "zh-CN" if market == "cn" else "en-US"})
            validate_purchase(order, product_id, purchase["orderNo"])
        purchase["orderNo"] = order["orderNo"]
        if order["status"] == "CLOSED":
            purchase["closed"] = True
        save_trial_state(product_id, state)
    # The first invocation always returns a QR before any wait. Polling cannot
    # create a new order, even when a local countdown has reached zero.
    deadline = time.monotonic() + wait if presented else time.monotonic()
    while order["status"] == "PENDING" and time.monotonic() < deadline:
        time.sleep(min(3, max(0, deadline - time.monotonic())))
        order = purchase_request(market, product_id, state, "status", {"orderNo": purchase["orderNo"]})
        validate_purchase(order, product_id, purchase["orderNo"])
    if order["status"] == "PAID":
        receipt = purchase_request(market, product_id, state, "download")
        access = receipt.get("access") or {}
        if access.get("owned") is not True or access.get("installKind") != "OWNED_PAID" or access.get("productId") != product_id:
            raise Failure("OWNED_DOWNLOAD_INVALID", "未确认当前商品的有效购买权益,不能安装正式版")
        result = finish_install(market, product_id, agent, access, receipt.get("download") or {}, "owned")
        remove_payment_artifacts(order["orderNo"])
        return result
    if order["status"] == "CLOSED":
        with ProductLock(product_id):
            current = require_trial_state(market, product_id)
            if (current.get("purchase") or {}).get("orderNo") == order["orderNo"]:
                current["purchase"]["closed"] = True
                save_trial_state(product_id, current)
        return emit_ok({"allowed": False, "orderNo": order["orderNo"], "nextAction": "PAYMENT_CLOSED"})
    presentation = payment_presentation(market, order)
    with ProductLock(product_id):
        current = require_trial_state(market, product_id)
        if (current.get("purchase") or {}).get("orderNo") != order["orderNo"]:
            raise Failure("PURCHASE_STATE_CHANGED", "本机订单恢复记录发生变化,请保留并重试")
        current["purchase"]["presented"] = True
        save_trial_state(product_id, current)
    return emit_ok({"allowed": False, "productId": product_id, "orderNo": order["orderNo"],
                    "amountCents": order["amountCents"], "expiresAt": order["expiresAt"],
                    "paymentPresentation": presentation, "nextAction": "PRESENT_PAYMENT_WIDGET",
                    "message": "先读取并展示 widgetPath 的 HTML,再运行同一 purchase 命令加 --wait 60 等待付款;超时保留原订单。"})


def shared_widget_resource(market, name):
    digest = WIDGET_DIGESTS[name]
    data = http_download(SCRIPT_ORIGIN[market] + "/skills/_widgets/sha256-%s/%s" % (digest, name))
    if hashlib.sha256(data).hexdigest() != digest:
        raise Failure("WIDGET_RESOURCE_INVALID", "支付展示资源完整性校验失败,保留原订单并重试")
    return data


def write_payment_artifact(order_no, suffix, data):
    directory = os.path.join(home_directory(), ".viceme", "payment-presentations")
    os.makedirs(directory, mode=0o700, exist_ok=True)
    path = os.path.join(directory, "wechat-" + hashlib.sha256(order_no.encode("utf-8")).hexdigest()[:32] + suffix)
    fd, temporary = tempfile.mkstemp(prefix=".payment-", dir=directory)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.remove(temporary)
    return os.path.abspath(path)


def remove_payment_artifacts(order_no):
    stem = "wechat-" + hashlib.sha256(order_no.encode("utf-8")).hexdigest()[:32]
    directory = os.path.join(home_directory(), ".viceme", "payment-presentations")
    for extension in ("html", "svg", "png"):
        try:
            os.unlink(os.path.join(directory, stem + "." + extension))
        except OSError:
            # A stale local display file cannot change a completed formal
            # install or the server's payment status. Never retry installation
            # solely because best-effort display cleanup was denied.
            pass


def payment_presentation(market, order):
    svg = ""
    action = order.get("paymentAction")
    if action is not None:
        uri = action.get("content", "") if isinstance(action, dict) else ""
        if not isinstance(uri, str) or len(uri) > 4096 or action.get("type") != "QR_CODE" or urllib.parse.urlsplit(uri).scheme != "weixin":
            raise Failure("PAYMENT_QR_INVALID", "订单未返回有效的微信支付二维码,保留原订单并重试")
        namespace = {"__name__": "viceme_qrcodegen"}
        exec(compile(shared_widget_resource(market, "qrcodegen.py"), "qrcodegen.py", "exec"), namespace)
        code = namespace["QrCode"].encode_text(uri, namespace["QrCode"].Ecc.MEDIUM)
        size = code.get_size() + 8
        path = "".join("M%d %dh1v1h-1z" % (x + 4, y + 4) for y in range(code.get_size()) for x in range(code.get_size()) if code.get_module(x, y))
        svg = '<svg xmlns="http://www.w3.org/2000/svg" role="img" aria-label="微信支付二维码" viewBox="0 0 %d %d" shape-rendering="crispEdges"><title>微信支付二维码</title><desc>使用微信扫一扫完成订单支付</desc><path fill="#fff" d="M0 0h%dv%dH0z"/><path fill="#000" d="%s"/></svg>' % (size, size, size, size, path)
    data = {"title": order["title"], "amountCents": order["amountCents"], "currency": order["currency"],
            "paymentMethodLabel": "微信支付", "status": order["status"], "expiresAt": order["expiresAt"], "locale": "zh-CN" if market == "cn" else "en-US"}
    encoded = json.dumps(data, ensure_ascii=True).replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")
    widget = shared_widget_resource(market, "payment.html").decode("utf-8").replace("__QR_SVG__", svg).replace("__WIDGET_DATA__", encoded)
    result = {"type": "LOCAL_IMAGE", "purpose": "PAYMENT_QR_CODE", "mimeType": "image/svg+xml",
              "widgetPath": write_payment_artifact(order["orderNo"], ".html", widget.encode("utf-8")),
              "widgetMimeType": "text/html", "expiresAt": order["expiresAt"], "altText": "微信支付二维码"}
    if svg:
        result["imagePath"] = write_payment_artifact(order["orderNo"], ".svg", svg.encode("utf-8"))
    return result


def validate_trial_use(use):
    valid = isinstance(use, dict) and type(use.get("allowed")) is bool
    if valid and use["allowed"]:
        valid = type(use.get("remainingUses")) is int and use["remainingUses"] >= 0 and type(use.get("limitUses")) is int and use["limitUses"] > 0
    elif valid:
        try:
            purchase = urllib.parse.urlsplit(use.get("purchaseUrl") or "")
            valid = use.get("reason") == "EXHAUSTED" and purchase.scheme in ("http", "https") and bool(purchase.netloc) and purchase.username is None
        except (TypeError, ValueError):
            valid = False
    if not valid:
        # 不确认 pending,更不能根据缺失字段或网络错误去停用本地技能。
        raise Failure("TRIAL_USE_RESPONSE_INVALID", "试用检查响应不完整,请重试本次检查")


# ---------------------------------------------------------------------------
# 解包与落盘(镜像 CLI 的安全约束)
# ---------------------------------------------------------------------------


def extract_skill_package(archive):
    try:
        reader = zipfile.ZipFile(io.BytesIO(archive))
    except zipfile.BadZipFile:
        raise Failure("ARCHIVE_INVALID", "Skill 包不是有效的 ZIP 文件") from None
    files = {}
    total = 0
    for info in reader.infolist():
        name = info.filename.replace("\\", "/")
        if not name or name.endswith("/"):
            continue
        mode = info.external_attr >> 16
        # Go zip 的 Mode() 语义:无类型位(0 或仅权限位)= 常规文件;
        # 只有显式非常规类型(符号链接/目录/设备)才拒绝。
        file_type = mode & 0o170000
        if name.startswith("/") or ".." in name.split("/") or os.path.normpath(name) != name.replace("/", os.sep) or (file_type and file_type != stat.S_IFREG):
            raise Failure("ARCHIVE_UNSAFE", "Skill 包包含不安全的路径: %s" % name)
        if len(files) >= MAX_FILES or info.file_size > MAX_FILE_BYTES:
            raise Failure("ARCHIVE_LIMIT_EXCEEDED", "Skill 包超出安全解包限制") from None
        try:
            data = reader.read(info)
        except (zipfile.BadZipFile, RuntimeError, OSError):
            raise Failure("ARCHIVE_INVALID", "Skill 包无法读取: %s" % name) from None
        if len(data) > MAX_FILE_BYTES:
            raise Failure("ARCHIVE_LIMIT_EXCEEDED", "Skill 包超出安全解包限制") from None
        total += len(data)
        if total > MAX_TOTAL_BYTES:
            raise Failure("ARCHIVE_LIMIT_EXCEEDED", "Skill 包超出安全解包限制") from None
        files[name] = (data, 0o755 if mode & 0o111 else 0o644)
    reader.close()
    if "SKILL.md" not in files:
        raise Failure("MANIFEST_MISSING", "Skill 包缺少根 SKILL.md")
    return files


def inject_trial_gate(files, market, product_id):
    data, mode = files["SKILL.md"]
    content = data.decode("utf-8", "replace").replace("\r\n", "\n")
    if not content.startswith("---\n"):
        raise Failure("MANIFEST_INVALID", "SKILL.md 必须以 YAML frontmatter 开始")
    end = (content + "\n").find("\n---\n", 4)
    if end < 0:
        raise Failure("MANIFEST_INVALID", "SKILL.md frontmatter 未闭合")
    insert_at = end + len("\n---\n")
    if insert_at > len(content):
        content += "\n"
    header = "%s product=%s -->" % (GATE_MARKER, product_id)
    runtime_header = "%s product=%s -->\n" % (RUNTIME_MARKER, product_id)
    if RUNTIME_PATH in files and not files[RUNTIME_PATH][0].startswith(runtime_header.encode("utf-8")):
        raise Failure("TRIAL_GATE_CONFLICT", "Skill 包中已有非本产品生成的 %s,不能覆盖" % RUNTIME_PATH)
    body = content[insert_at:]
    if body.startswith(GATE_MARKER + " product="):
        if not body.startswith(header + "\n"):
            raise Failure("TRIAL_GATE_CONFLICT", "Skill 包包含其他产品的使用检查")
        gate_end = "\n" + GATE_END + "\n"
        end = body.find(gate_end)
        if end >= 0:
            body = body[end + len(gate_end):]
        elif GATE_TAIL + "\n\n" in body and "## 试用版使用规则（viceme-trial）" in body.split(GATE_TAIL, 1)[0]:
            # 迁移旧内联规则,只删除有完整边界的生成段,保留作者正文。
            body = body.split(GATE_TAIL + "\n\n", 1)[1]
        else:
            raise Failure("TRIAL_GATE_INVALID", "Skill 包中的使用检查不完整")
    script = script_url(market)
    posix_use = "curl -fsSL %s | python3 - use --product %s --market %s" % (script, product_id, market)
    windows_use = (
        "curl.exe -fsSL %s -o $env:TEMP\\viceme-trial.py; "
        "py $env:TEMP\\viceme-trial.py use --product %s --market %s" % (script, product_id, market)
    )
    section = (
        "%s\n\n## 使用前必读\n\n"
        "每次开始或继续本技能任务前，必须先读取并执行 [使用前检查](%s)，判断是否属于同一已放行的使用单元。只有本使用单元的检查明确返回 `allowed: true` 才能执行下方任务；未放行、次数用完或检查失败时停止，不得跳过检查，也不得以安装成功或其他任务的历史检查代替本次授权。\n\n%s\n"
    ) % (header, RUNTIME_PATH, GATE_END)
    rules = (
        "%s\n# 使用前检查\n\n"
        "本技能当前是 ViceMe 试用版。先读取[统一计次规则](%s)，由 Agent 判断独立使用单元。同一已放行任务的内部步骤、澄清和修订不重复计次；安装、介绍、示例展示和查询余额不计次。不得沿用其他任务的授权。\n\n"
        "1. 本机没有可用的 Python（POSIX 环境的 `python3`，Windows 的 `py` 或 `python`），或下面的检查命令无法成功运行时，不得跳过检查直接使用本技能：停止使用，向用户说明需要先安装 Python，或按官方安装契约 %s 安装 ViceMe CLI 并改用 `viceme skill use %s --wait 0`。\n"
        "2. 按本机环境运行下面的检查命令。只有本次输出明确返回 `allowed: true` 才能继续；错误、无结果或 `allowed: false` 均不得执行技能任务，即使用户要求跳过也不例外：\n"
        "   - macOS / Linux（POSIX shell）：`%s`\n"
        "   - Windows（PowerShell，`py` 不可用时改用 `python`）：`%s`\n"
        "3. 每个新使用单元执行前预检，记录任务和返回的 requestId。放行后告知「本次是第 X / N 次试用」，X = limitUses - remainingUses。任务完成后提示剩余次数；最后一次仍完整完成本次任务，提醒下次需付费。仅查询余额把上述命令的 use 换成 status，不得调用 use 来查询。\n"
        "4. 试用用完时停止任务，把上述命令的 use 换成 purchase 并加 --wait 0 创建或恢复订单；按[通用 Widget 指引](%s)先展示返回的 widgetPath，再用同一 purchase 命令加 --wait 60 有界等待付款。无需 CLI 或强制登录。二维码过期或用户说已付款不是到账证明。只有服务端确认付款与有效权益、脚本成功安装完整正式包后，重新读取 SKILL.md，再继续原任务。\n"
    ) % (runtime_header, script.rsplit("use-a-skill/", 1)[0] + "use-a-skill/references/trial-usage.md", install_doc_url(market), product_id, posix_use, windows_use, script.rsplit("use-a-skill/", 1)[0] + "_widgets/README.md")
    files["SKILL.md"] = ((content[:insert_at] + section + body).encode("utf-8"), mode)
    files[RUNTIME_PATH] = (rules.encode("utf-8"), 0o644)


def verify_installed_trial_gate(root, files):
    for name in ("SKILL.md", RUNTIME_PATH):
        try:
            with open(os.path.join(root, *name.split("/")), "rb") as handle:
                valid = handle.read() == files[name][0]
        except OSError:
            valid = False
        if not valid:
            raise Failure("TRIAL_GATE_INVALID", "使用检查未完整写入,请重新安装后再使用", file=name)


def suspension_roots():
    # 不按当前调用方筛选:该商品之前可能由另一工具安装。包含 Go 支持的
    # 自定义根,但从不遍历根目录之外或猜测任意用户工作区。
    roots = target_roots("all")
    for variable in ("CODEX_HOME", "CLAUDE_CONFIG_DIR", "WORKBUDDY_CONFIG_DIR"):
        if os.environ.get(variable):
            roots.append(os.path.join(os.environ[variable], "skills"))
    if os.environ.get("VICEME_AGENTS_SKILLS_DIR"):
        roots.append(os.environ["VICEME_AGENTS_SKILLS_DIR"])
    return sorted({os.path.realpath(root) for root in roots})


def trial_product_owns_directory(directory, product_id):
    manifest_path = os.path.join(directory, ".viceme", "install-manifest.json")
    try:
        for path in (directory, os.path.join(directory, ".viceme"), manifest_path):
            if stat.S_ISLNK(os.lstat(path).st_mode):
                return False
        with open(manifest_path, encoding="utf-8") as handle:
            manifest = json.load(handle)
        return isinstance(manifest, dict) and manifest.get("product_id") == product_id and bool(manifest.get("release_id"))
    except (OSError, ValueError):
        return False


def suspended_trial_markdown(original, skill_name, product_id, purchase_url, market):
    if frontmatter_name({"SKILL.md": (original, 0o644)}) != skill_name:
        return None
    lines = original.splitlines(keepends=True)
    if not lines or lines[0].rstrip(b"\r\n") != b"---":
        return None
    for index in range(1, len(lines)):
        if lines[index].rstrip(b"\r\n") == b"---":
            prefix = b"".join(lines[:index + 1])
            break
    else:
        return None
    try:
        body = original[len(prefix):].decode("utf-8").replace("\r\n", "\n").lstrip("\n")
    except UnicodeDecodeError:
        return None
    disabled = "%s product=%s -->" % (DISABLED_MARKER, product_id)
    if body.startswith(disabled + "\n"):
        return original
    active = "%s product=%s -->\n\n" % (GATE_MARKER, product_id)
    if not body.startswith((active + "## 使用前必读\n", active + "## 试用版使用规则（viceme-trial）\n")):
        return None
    safe_url = purchase_url.replace("<", "%3C").replace(">", "%3E").replace("\r", "%0D").replace("\n", "%0A")
    notice = (
        "%s\n\n# 试用已结束\n\n"
        "本技能的免费试用次数已用完，当前已停用。不得继续执行原技能任务，也不得调用目录中保留的脚本或参考资料来继续试用。\n\n"
        "读取 [使用前检查](references/viceme-runtime.md) 中的购买指引，按原预检路线创建或恢复订单，先展示支付 Widget，再有界等待到账并安装完整正式包；无需强制登录。[商品页面](<%s>)仅供查看商品。若已通过账号购买，按[官方安装说明](<%s>)使用 `viceme skill install %s --owned` 校验该账号权益并安装。\n\n"
        "正式版安装成功后，重新读取 SKILL.md 再继续任务。重装试用版不会恢复试用次数。\n"
    ) % (disabled, safe_url, install_doc_url(market), product_id)
    if original.startswith(b"---\r\n"):
        notice = notice.replace("\n", "\r\n")
    return prefix + notice.encode("utf-8")


def suspend_trial_skills(market, product_id, purchase_url):
    """调用方持有 ProductLock;只替换同 Product 的已确认试用入口。"""
    count = 0
    try:
        for root in suspension_roots():
            try:
                with os.scandir(root) as scan:
                    directories = sorted(entry.path for entry in scan if "." not in entry.name and entry.is_dir(follow_symlinks=False))
            except FileNotFoundError:
                continue
            for directory in directories:
                if not trial_product_owns_directory(directory, product_id):
                    continue
                with skill_path_lock(directory):
                    count += int(suspend_trial_entry(directory, market, product_id, purchase_url))
    except OSError:
        raise Failure(
            "TRIAL_SUSPEND_FAILED", "试用已用完,但未能安全停用全部入口;请停止使用,通过宿主授权后重试,或安装已购正式版",
            disabledSkillCount=count,
        ) from None
    return count


@contextmanager
def skill_path_lock(directory):
    # 镜像 skillcontent.installPathLockFilename 与 gofrs/flock:Unix flock,
    # Windows 在 offset 0 锁 1 字节。覆盖不持有 ProductLock 的原生安装恢复。
    normalized = os.path.realpath(directory)
    if os.name == "nt":
        normalized = normalized.lower()
    digest = hashlib.sha256(normalized.encode("utf-8")).hexdigest()
    lock_path = os.path.join(os.path.dirname(normalized), ".viceme-install-%s.lock" % digest)
    descriptor = os.open(lock_path, os.O_RDWR | os.O_CREAT, 0o600)
    try:
        if os.name == "nt":
            import msvcrt
            msvcrt.locking(descriptor, msvcrt.LK_NBLCK, 1)
        else:
            import fcntl
            fcntl.flock(descriptor, fcntl.LOCK_EX | fcntl.LOCK_NB)
        try:
            with open(lock_path + ".owner", encoding="utf-8") as handle:
                owner = handle.read()
                if owner.endswith("\n"):
                    owner = owner[:-1]
        except FileNotFoundError:
            owner = None
        if owner is not None and (not os.path.isabs(owner) or "\n" in owner or "\r" in owner or os.path.lexists(owner)):
            raise OSError("an unfinished install transaction owns the Skill")
        yield
    finally:
        os.close(descriptor)  # Closing releases the process lock, not its file.


def suspend_trial_entry(directory, market, product_id, purchase_url):
    if not trial_product_owns_directory(directory, product_id):
        return False
    filename = os.path.join(directory, "SKILL.md")
    try:
        info = os.lstat(filename)
    except FileNotFoundError:
        return False
    if not stat.S_ISREG(info.st_mode):
        return False
    with open(filename, "rb") as handle:
        original = handle.read()
    replacement = suspended_trial_markdown(original, os.path.basename(directory), product_id, purchase_url, market)
    if replacement is None:
        return False
    if replacement == original:
        return True
    staged = None
    try:
        with tempfile.NamedTemporaryFile(mode="wb", prefix=".viceme-trial-suspend-", dir=directory, delete=False) as handle:
            staged = handle.name
            handle.write(replacement)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(staged, stat.S_IMODE(info.st_mode))
        with open(filename, "rb") as handle:
            unchanged = handle.read() == original
        if not unchanged or not trial_product_owns_directory(directory, product_id):
            raise OSError("Skill changed before trial suspension")
        # 不退回原地截断:权限拒绝时保留完整旧文件,交给宿主审批。
        os.replace(staged, filename)
        staged = None
        with open(filename, "rb") as handle:
            if handle.read() != replacement:
                raise OSError("trial suspension readback failed")
        return True
    finally:
        if staged is not None:
            try:
                os.remove(staged)
            except OSError:
                pass


def frontmatter_name(files):
    content = files["SKILL.md"][0].decode("utf-8", "replace").replace("\r\n", "\n")
    lines = content.split("\n")
    if len(lines) < 3 or lines[0].strip() != "---":
        return ""
    for index in range(1, len(lines)):
        if lines[index].strip() == "---":
            block = lines[1:index]
            break
    else:
        return ""
    for line in block:
        if line.startswith("name:"):
            value = line[5:].strip().strip('"').strip("'")
            return value
    return ""


def slugify(title):
    slug = ""
    for character in (title or "").strip().lower():
        slug += character if ("a" <= character <= "z" or "0" <= character <= "9") else "-"
    while "--" in slug:
        slug = slug.replace("--", "-")
    return slug.strip("-")


def resolve_installed_name(files, access):
    if slug := slugify(frontmatter_name(files)):
        return slug
    edition = access.get("edition") or {}
    if slug := slugify(edition.get("title") or ""):
        return slug
    compact = access.get("productId", "").replace("-", "")[:8]
    return "viceme-" + compact if compact else "viceme-skill"


# 调用方是谁就只装谁家,不往用不到的目录扩散。三家标记均为实测:
# WorkBuddy 执行环境带 CODEBUDDY_*(它是 CodeBuddy 血统);Codex 设
# CODEX_SESSION_ID/THREAD_ID/SANDBOX;Claude 有 CLI 版 CLAUDECODE 与
# Desktop agent 版 AI_AGENT=claude-code_*,两套都要认。识别不到时退回
# 与 CLI auto 一致的全量语义(agents 恒装 + 存在的各家)。
AGENT_ENV_MARKERS = {
    "workbuddy": ("CODEBUDDY_SESSION_ID", "CODEBUDDY_SANDBOX_BROKER_SESSION_ID", "WORKBUDDY_SESSION_ID"),
    "codex": ("CODEX_SESSION_ID", "CODEX_THREAD_ID", "CODEX_SANDBOX"),
    "claude": ("CLAUDECODE", "CLAUDE_AGENT_SDK_VERSION"),
}


def detect_invoking_agent():
    for agent, markers in AGENT_ENV_MARKERS.items():
        if any(os.environ.get(marker) for marker in markers):
            return agent
    ai_agent = os.environ.get("AI_AGENT") or ""
    if ai_agent.startswith("claude-code"):
        return "claude"
    return ""


def target_roots(agent="auto"):
    home = home_directory()
    if agent == "auto":
        agent = detect_invoking_agent()
    known = {
        "workbuddy": os.path.join(home, ".workbuddy", "skills"),
        "codex": os.path.join(home, ".codex", "skills"),
        "claude": os.path.join(home, ".claude", "skills"),
    }
    if agent in known:
        return [known[agent]]
    roots = [os.path.join(home, ".agents", "skills")]
    for base in (".codex", ".claude", ".workbuddy"):
        if os.path.isdir(os.path.join(home, base)):
            roots.append(os.path.join(home, base, "skills"))
    return roots


def install_to_roots(files, installed_name, product_id, release_id, agent="auto"):
    results = []
    for root in target_roots(agent):
        destination = os.path.join(root, installed_name)
        os.makedirs(root, exist_ok=True)
        owner = read_manifest_product(destination)
        if owner is None:
            results.append((destination, "skipped: 目录已存在且非 ViceMe 管理,拒绝覆盖"))
            continue
        if owner and owner != product_id:
            results.append((destination, "skipped: 目录属于其他 Product(%s),拒绝覆盖" % owner))
            continue
        if owner == product_id:
            overwrite_in_place(files, installed_name, destination, product_id, release_id)
            results.append((destination, ""))
            continue
        staged = stage_skill(files, installed_name, product_id, release_id, root)
        backup = destination + ".viceme-script-backup"
        remove_path(backup)
        if os.path.exists(destination):
            os.rename(destination, backup)
        try:
            # staged 是临时外壳,里面才是同名技能目录;搬运内层,
            # 外壳随后清掉。
            os.rename(os.path.join(staged, installed_name), destination)
        except OSError:
            if os.path.exists(backup) and not os.path.exists(destination):
                os.rename(backup, destination)
            remove_path(staged)
            results.append((destination, "skipped: 写入失败"))
            continue
        remove_path(backup)
        remove_path(staged)
        results.append((destination, ""))
    return results


def install_owned_to_roots(files, installed_name, product_id, release_id, agent="auto"):
    """Activate the formal entry last, without bulk-deleting local user files.

    Caller holds ProductLock. Each target also uses the Go-compatible path
    lock. All formal bytes are already verified. Until every supporting file
    is written, the old suspended/trial entry stays in place. A denied write
    therefore cannot activate a partially prepared formal entry.
    """
    complete = compose_skill_files(files, installed_name, product_id, release_id)
    results = []
    for root in target_roots(agent):
        os.makedirs(root, mode=0o700, exist_ok=True)
        destination = os.path.join(root, installed_name)
        with skill_path_lock(destination):
            owner = read_manifest_product(destination)
            if owner is None or (owner and owner != product_id) or os.path.islink(destination):
                results.append((destination, "skipped: 目标不属于当前 Product,拒绝覆盖"))
                continue
            os.makedirs(destination, mode=0o755, exist_ok=True)
            for name in sorted(complete, key=lambda name: (name == "SKILL.md", name)):
                path = destination
                for component in name.split("/"):
                    path = os.path.join(path, component)
                    if os.path.islink(path):
                        raise Failure("INSTALL_UNSAFE_PATH", "正式包安装目标包含符号链接,保留原入口并停止")
                os.makedirs(os.path.dirname(path), mode=0o700, exist_ok=True)
                fd, temporary = tempfile.mkstemp(prefix=".viceme-formal-", dir=os.path.dirname(path))
                try:
                    data, mode = complete[name]
                    with os.fdopen(fd, "wb") as handle:
                        handle.write(data)
                        handle.flush()
                        os.fsync(handle.fileno())
                    os.chmod(temporary, mode)
                    os.replace(temporary, path)
                finally:
                    if os.path.exists(temporary):
                        os.remove(temporary)
            # Only our generated reference is removable. Never sweep files
            # omitted by the formal package: they may be user-created output.
            runtime_path = os.path.join(destination, RUNTIME_PATH)
            if RUNTIME_PATH not in complete and not os.path.islink(runtime_path):
                try:
                    with open(runtime_path, "rb") as handle:
                        generated = handle.read().startswith((RUNTIME_MARKER + " product=" + product_id + " -->").encode())
                    if generated:
                        os.remove(runtime_path)
                except FileNotFoundError:
                    pass
            results.append((destination, ""))
    return results


def read_manifest_product(destination):
    """返回目的目录的 manifest product_id;None=不可覆盖,False=全新目录。"""
    if not os.path.isdir(destination):
        return False
    try:
        with open(os.path.join(destination, ".viceme", "install-manifest.json"), "r", encoding="utf-8") as handle:
            manifest = json.load(handle)
    except (OSError, ValueError):
        return None
    product = manifest.get("product_id")
    if not product:
        return None
    return product


def compose_skill_files(files, installed_name, product_id, release_id):
    """包文件 + 平台合成文件的完整清单(name -> (bytes, mode))。"""
    complete = dict(files)
    if "agents/openai.yaml" not in complete:
        complete["agents/openai.yaml"] = (
            (
                'interface:\n  display_name: "%s"\n  short_description: "Use this verified ViceMe Skill edition"\n  default_prompt: "Use $%s to continue the current task."\n'
                % (installed_name.replace('"', '\\"'), installed_name.replace('"', '\\"'))
            ).encode("utf-8"),
            0o600,
        )
    complete["skill-package.json"] = (
        (
            json.dumps(
                {"schema_version": 1, "skill_version": "1", "minimum_cli_version": "", "cli_compatibility": "script"},
                indent=2,
            )
            + "\n"
        ).encode("utf-8"),
        0o600,
    )
    # 与 CLI 的 installManifest 字段对齐;溯源守卫只认 product_id/release_id,
    # 版本/摘要字段留空表示「由免 CLI 脚本安装」,CLI 转正重装时会重写完整清单。
    complete[".viceme/install-manifest.json"] = (
        (
            json.dumps(
                {
                    "schema_version": 1,
                    "cli_version": "viceme-trial-script/1",
                    "skill_version": "1",
                    "minimum_cli_version": "",
                    "cli_compatibility": "script",
                    "full_skill_bundle_digest": "",
                    "embedded_content_digest": "",
                    "product_id": product_id,
                    "release_id": release_id,
                },
                indent=2,
            )
            + "\n"
        ).encode("utf-8"),
        0o644,
    )
    return complete


def stage_skill(files, installed_name, product_id, release_id, root):
    staged = tempfile.mkdtemp(prefix=installed_name + ".viceme-script-", dir=root)
    skill_dir = os.path.join(staged, installed_name)
    os.makedirs(skill_dir, mode=0o700)
    for name, (data, mode) in sorted(compose_skill_files(files, installed_name, product_id, release_id).items()):
        destination = os.path.join(skill_dir, *name.split("/"))
        os.makedirs(os.path.dirname(destination), mode=0o700, exist_ok=True)
        with open(destination, "wb") as handle:
            handle.write(data)
        os.chmod(destination, mode)
    os.chmod(skill_dir, 0o755)
    os.chmod(staged, 0o755)
    return staged


def overwrite_in_place(files, installed_name, destination, product_id, release_id):
    """同款重装:原地覆写,只删新版没有的文件。

    整目录换建(备份→替换→删备份)会把旧安装全部计入"删除",触发执行
    环境的批量删除护栏(WorkBuddy 沙箱阈值 50 项)并吓到用户;原地覆写
    让重装同版本的删除数为零,升级时只清理作者真正移除的文件。
    """
    complete = compose_skill_files(files, installed_name, product_id, release_id)
    wanted_dirs = set()
    for name in complete:
        parts = name.split("/")
        for depth in range(1, len(parts)):
            wanted_dirs.add(os.path.join(destination, *parts[:depth]))
    for name in sorted(complete):
        path = os.path.join(destination, *name.split("/"))
        os.makedirs(os.path.dirname(path), mode=0o700, exist_ok=True)
        data, mode = complete[name]
        with open(path, "wb") as handle:
            handle.write(data)
        os.chmod(path, mode)
    for current, _dirnames, filenames in os.walk(destination, topdown=False):
        for filename in filenames:
            path = os.path.join(current, filename)
            relative = os.path.relpath(path, destination).replace(os.sep, "/")
            if relative not in complete:
                os.remove(path)
        if current != destination and current not in wanted_dirs and not os.listdir(current):
            os.rmdir(current)


def remove_path(path):
    if not os.path.exists(path) and not os.path.islink(path):
        return
    if os.path.isdir(path) and not os.path.islink(path):
        import shutil

        shutil.rmtree(path, ignore_errors=True)
    else:
        try:
            os.remove(path)
        except OSError:
            pass


# ---------------------------------------------------------------------------
# 入口
# ---------------------------------------------------------------------------


def parse_args(argv):
    parser = argparse.ArgumentParser(prog="trial.py", description="ViceMe Skill 免 CLI 安装与试用计数")
    parser.add_argument("command", choices=["install", "use", "status", "purchase"], help="install=安装,use=申请一次试用,status=查询余量不扣次,purchase=付款并转正")
    parser.add_argument("--wait", type=int, default=0, help="已展示二维码后有界等待支付的秒数(0–600)")
    parser.add_argument("--product", required=True, help="Skill 的 Product ID(UUID)")
    parser.add_argument("--market", choices=sorted(SCRIPT_ORIGIN), default="cn", help="市场区域:cn 或 global")
    parser.add_argument(
        "--agent",
        choices=["auto", "workbuddy", "codex", "claude", "agents"],
        default="auto",
        help="安装目标:auto=按调用方环境自动定向(识别不到时装全部标准目录)",
    )
    return parser.parse_args(argv)


def main(argv):
    args = parse_args(argv)
    try:
        if str(uuid.UUID(args.product)) != args.product.lower() or not 0 <= args.wait <= 600:
            raise ValueError()
    except ValueError:
        raise Failure("ARGUMENT_INVALID", "商品 ID 必须为 UUID,等待时间必须在 0–600 秒之间") from None
    if args.command == "install":
        return command_install(args.market, args.product, args.agent)
    if args.command == "status":
        return command_status(args.market, args.product)
    if args.command == "purchase":
        return command_purchase(args.market, args.product, args.wait, args.agent)
    return command_use(args.market, args.product)


def run(argv):
    """入口包装:任何失败(含未预期异常)都以单行 JSON 收场。"""
    try:
        return main(argv)
    except Failure as failure:
        return emit_failure(failure)
    except KeyboardInterrupt:
        return 130
    except Exception as error:  # noqa: BLE001 - 脚本契约:任何失败都输出单行 JSON
        # 固定文案+异常类型名:原始错误文字可能携带用户目录、内部路径等
        # 本机信息,不得进 AI 对话或日志。
        return emit_failure(Failure("UNEXPECTED_ERROR", "脚本异常退出(%s),请重试;持续失败请安装 ViceMe CLI 使用完整流程" % type(error).__name__))


if __name__ == "__main__":
    sys.exit(run(sys.argv[1:]))
